# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            VEnis blog
tagline:          'A Jekyll theme'
description:      ''
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Vyacheslav Enis'
  url:            https://twitter.com/venis

paginate:         5

exclude: [vendor,Gemfile,Gemfile.lock,Rakefile]

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
